### ISSUE TITLE
 java.lang.NoSuchFieldError: No field bankEditText

### ISSUE THREAD

**Issue by estyne** [Flutterwave/rave-android#12]
Hello, am getting this error on initialization of the sdk

java.lang.NoSuchFieldError: No field bankEditText of type I in class Lcom/flutterwave/raveandroid/R$id; or its superclasses (declaration of 'com.flutterwave.raveandroid.R$id'

**Comment by biodunalfet** [comment]
Do you have any layouts named fragment_account.xml?

**Comment by estyne** [comment]
I already solved it

**Comment by Arahanad** [comment]
How to solve this ?

**Comment by biodunalfet** [comment]
@Arahanad Are you having this issue also?

**Comment by Arahanad** [comment]
Yes

**Comment by biodunalfet** [comment]
@Arahanad what version of the sdk are you using?

**Comment by Arahanad** [comment]
Sdk 7.1

**Comment by biodunalfet** [comment]
@Arahanad I meant what version of rave-android sdk are you using? Are you using the latest version? 
`compile 'com.github.Flutterwave:rave-android:1.0.18'`

**Comment by Arahanad** [comment]
Yeah latest

**Comment by Arahanad** [comment]
Sry i have fragment_account.xml file

**Comment by biodunalfet** [comment]
@Arahanad Can you paste the exact error you're getting?

**Comment by biodunalfet** [comment]
@Arahanad fixed?

**Comment by Arahanad** [comment]
sorry about late
here's error
java.lang.NoSuchFieldError: No field rave_bankEditText of type I in class Lcom/flutterwave/raveandroid/R$id; or its superclasses (declaration of 'com.flutterwave.raveandroid.R$id' appears in /data/app/com.ankur.jibiyality-2/split_lib_slice_3_apk.apk)
        at com.flutterwave.raveandroid.account.AccountFragment.onCreateView(AccountFragment.java:107)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:739)
        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:811)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:693)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2316)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1407)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1660)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1295)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6400)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
        at android.view.Choreographer.doCallbacks(Choreographer.java:688)
        at android.view.Choreographer.doFrame(Choreographer.java:623)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6221)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by biodunalfet** [comment]
@Arahanad It means you have a file named fragment_account.xml in your project. Can you rename it?

**Comment by Arahanad** [comment]
is it necessary ? or there is other solution ?

**Comment by Arahanad** [comment]
after renaming it is working thanks. But i'm looking for any other solution.

**Comment by biodunalfet** [comment]
@Arahanad I will do a fix in the next update that'll reduce the chances of people encountering this
