### ISSUE TITLE
Account payment button causes app to crash

### ISSUE THREAD

**Issue by Akinbode99** [Flutterwave/rave-android#121]
Hi there, Whenever i want to make test Account payments, after i must have successfully filled in all the details and have selected the bank it takes me to the OTP page, however while on the OTP page, my app crashes here's the log 
10-08 15:30:06.581 28714-28714/com.emmaflow.hubryde.hubryde E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.emmaflow.hubryde.hubryde, PID: 28714
    java.lang.NullPointerException: Attempt to invoke virtual method 'void 
  android.os.Bundle.unparcel()' on a null object reference
        at android.os.Bundle.putAll(Bundle.java:182)
        at com.flutterwave.raveandroid.banktransfer.BankTransferFragment.onSaveInstanceState(BankTransferFragment.java:219)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2766)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2289)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2348)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:151)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:513)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:533)
        at android.app.Activity.performSaveInstanceState(Activity.java:1304)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1300)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4339)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3723)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3791)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5765)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by biodunalfet** [comment]
@Akinbode99 have you been able to resolve this?

**Comment by Akinbode99** [comment]
yes,i got in contact with the team, they found the error and they'd
integrate a solution in the next release of the sdk
