### ISSUE TITLE
Can't make card payments, affects latest version 1.0.16 and previous versions. 

### ISSUE THREAD

**Issue by andela-Kshittu** [Flutterwave/rave-android#20]
I'm unable to perform successful card charge, it returns error after entering card pin. I think this might be due to changes in api. cos we had the same issue on ios sdk, but was resolved after updating to recent version of the ios sdk. see attached screenshots for more details.

![img-20180316-wa0006](https://user-images.githubusercontent.com/8383678/37553191-34a8c0f4-29c3-11e8-8f4d-e78485326eca.jpg)

**Comment by andela-Kshittu** [comment]
You probably need to discuss with the backend guys, I noticed the charge endpoint was returning html : 
```03-17 08:24:12.582 5195-5401/com.skye9.movies D/OkHttp: --> END POST (610-byte body)
03-17 08:24:42.793 5195-5401/com.skye9.movies D/OkHttp: <-- 503 Service Unavailable https://rave-api.herokuapp.com/flwv3-pug/getpaidx/api/charge (30210ms)
03-17 08:24:42.793 5195-5401/com.skye9.movies D/OkHttp: Connection: keep-alive
03-17 08:24:42.793 5195-5401/com.skye9.movies D/OkHttp: Server: Cowboy
03-17 08:24:42.793 5195-5401/com.skye9.movies D/OkHttp: Date: Sat, 17 Mar 2018 08:24:48 GMT
03-17 08:24:42.793 5195-5401/com.skye9.movies D/OkHttp: Content-Length: 506
03-17 08:24:42.793 5195-5401/com.skye9.movies D/OkHttp: Content-Type: text/html; charset=utf-8
03-17 08:24:42.793 5195-5401/com.skye9.movies D/OkHttp: Cache-Control: no-cache, no-store
03-17 08:24:42.795 5195-5401/com.skye9.movies D/OkHttp: <!DOCTYPE html>
03-17 08:24:42.795 5195-5401/com.skye9.movies D/OkHttp: 	<html>
03-17 08:24:42.795 5195-5401/com.skye9.movies D/OkHttp: 	  <head>
03-17 08:24:42.795 5195-5401/com.skye9.movies D/OkHttp: 		<meta name="viewport" content="width=device-width, initial-scale=1">
03-17 08:24:42.795 5195-5401/com.skye9.movies D/OkHttp: 		<meta charset="utf-8">
03-17 08:24:42.795 5195-5401/com.skye9.movies D/OkHttp: 		<title>Application Error</title>
03-17 08:24:42.795 5195-5401/com.skye9.movies D/OkHttp: 		<style media="screen">
03-17 08:24:42.795 5195-5401/com.skye9.movies D/OkHttp: 		  html,body,iframe {
03-17 08:24:42.795 5195-5401/com.skye9.movies D/OkHttp: 			margin: 0;
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 			padding: 0;
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 		  }
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 		  html,body {
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 			height: 100%;
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 			overflow: hidden;
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 		  }
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 		  iframe {
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 			width: 100%;
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 			height: 100%;
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 			border: 0;
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 		  }
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 		</style>
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 	  </head>
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 	  <body>
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 	  </body>
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: 	</html>
03-17 08:24:42.796 5195-5401/com.skye9.movies D/OkHttp: <-- END HTTP (506-byte body)
03-17 08:24:42.860 5195-5195/com.skye9.movies W/System.err: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
03-17 08:24:42.861 5195-5195/com.skye9.movies W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
03-17 08:24:42.861 5195-5195/com.skye9.movies W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:887)
03-17 08:24:42.861 5195-5195/com.skye9.movies W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:852)
03-17 08:24:42.861 5195-5195/com.skye9.movies W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:801)
03-17 08:24:42.861 5195-5195/com.skye9.movies W/System.err:     at com.flutterwave.raveandroid.data.NetworkRequestImpl.parseErrorJson(NetworkRequestImpl.java:49)
03-17 08:24:42.861 5195-5195/com.skye9.movies W/System.err:     at com.flutterwave.raveandroid.data.NetworkRequestImpl.access$000(NetworkRequestImpl.java:37)
03-17 08:24:42.862 5195-5195/com.skye9.movies W/System.err:     at com.flutterwave.raveandroid.data.NetworkRequestImpl$2.onResponse(NetworkRequestImpl.java:79)
03-17 08:24:42.863 5195-5195/com.skye9.movies W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
03-17 08:24:42.863 5195-5195/com.skye9.movies W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
03-17 08:24:42.863 5195-5195/com.skye9.movies W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-17 08:24:42.863 5195-5195/com.skye9.movies W/System.err:     at android.os.Looper.loop(Looper.java:154)
03-17 08:24:42.864 5195-5195/com.skye9.movies W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
03-17 08:24:42.864 5195-5195/com.skye9.movies W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-17 08:24:42.864 5195-5195/com.skye9.movies W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
03-17 08:24:42.864 5195-5195/com.skye9.movies W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
03-17 08:24:42.864 5195-5195/com.skye9.movies W/System.err: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
03-17 08:24:42.864 5195-5195/com.skye9.movies W/System.err:     at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
03-17 08:24:42.864 5195-5195/com.skye9.movies W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)```

**Comment by biodunalfet** [comment]
Hi @andela-Kshittu Thanks for raising this issue. It has been resolved
