### ISSUE TITLE
Android app crash

### ISSUE THREAD

**Issue by rohitsinglailluminz** [Flutterwave/rave-android#214]
I am using latest version of sdk -
implementation 'com.github.Flutterwave.rave-android:rave_android:2.1.1'

App is crashing on changing payment method - 

  java.lang.IllegalStateException: Fragment CardFragment{423c433} (23c21189-f963-4fab-bb19-5a0d4b42b011)} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
        at com.flutterwave.raveandroid.card.CardFragment.setUpSavedCardsAdapter(CardFragment.java:554)
        at com.flutterwave.raveandroid.card.CardFragment.setHasSavedCards(CardFragment.java:538)
        at com.flutterwave.raveandroid.card.CardFragment.onSavedCardsLookupFailed(CardFragment.java:660)
        at com.flutterwave.raveandroid.rave_presentation.card.CardPaymentHandler$7.onError(CardPaymentHandler.java:403)
        at com.flutterwave.raveandroid.rave_remote.RemoteRepository$GenericNetworkCallback.onError(RemoteRepository.java:355)
        at com.flutterwave.raveandroid.rave_java_commons.NetworkRequestExecutor$1.onResponse(NetworkRequestExecutor.java:47)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
        at android.os.Handler.handleCallback(Handler.java:869)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6784)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)

**NOTE** : Till yet did'nt found crash on degrading sdk to 
implementation 'com.github.Flutterwave.rave-android:rave_android:2.1.0'

**Comment by bolaware** [comment]
Heyy @rohitsinglailluminz, Sorry can you confirm this build fixes your issue implementation 'com.github.bolaware.rave-android:rave_android:2.1.2'?

**Comment by rohitsinglailluminz** [comment]
Hi @bolaware , thanks for quick response 

after updating sdk to 'com.github.bolaware.rave-android:rave_android:2.1.2'

Getting crash - 

 java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.content.Context.getDrawable(int)' on a null object reference
        at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:454)
        at com.flutterwave.raveandroid.SwipeToDeleteCallback.<init>(SwipeToDeleteCallback.java:35)
        at com.flutterwave.raveandroid.card.CardFragment$5.<init>(CardFragment.java:554)
        at com.flutterwave.raveandroid.card.CardFragment.setUpSavedCardsAdapter(CardFragment.java:554)
        at com.flutterwave.raveandroid.card.CardFragment.setHasSavedCards(CardFragment.java:538)
        at com.flutterwave.raveandroid.card.CardFragment.onSavedCardsLookupFailed(CardFragment.java:660)
        at com.flutterwave.raveandroid.rave_presentation.card.CardPaymentHandler$7.onError(CardPaymentHandler.java:403)
        at com.flutterwave.raveandroid.rave_remote.RemoteRepository$GenericNetworkCallback.onParseError(RemoteRepository.java:373)
        at com.flutterwave.raveandroid.rave_remote.RemoteRepository$GenericNetworkCallback.onError(RemoteRepository.java:359)
        at com.flutterwave.raveandroid.rave_java_commons.NetworkRequestExecutor$1.onResponse(NetworkRequestExecutor.java:47)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by bolaware** [comment]
@rohitsinglailluminz Hello, sorry for this back and forth. I cant replicate the crash, but I know why it's happening, kindly upgrade the build i gave you to 2.1.3 to test again and let me know

**Comment by rohitsinglailluminz** [comment]
@bolaware for sdk 2.1.3 did'nt get crash yet.
It is working good now.

**Comment by bolaware** [comment]
@bolaware Before i close this, help me check 2.1.4 works. It fixes the temporary delay when showing the saved cards.
