### ISSUE TITLE
GHANA Payments are DOWN

### ISSUE THREAD

**Issue by mugabi0978** [Flutterwave/rave-android#216]
{"status":"00","statusdec":"Event Saved"}
2020-07-17 17:45:33.638 21528-30669/com.flutterwave.rave_android D/OkHttp: <-- END HTTP (41-byte body)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:944)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:897)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:846)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at com.flutterwave.raveandroid.rave_java_commons.NetworkRequestExecutor$1.onResponse(NetworkRequestExecutor.java:40)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at android.os.Looper.loop(Looper.java:237)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7762)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err: Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:932)
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android W/System.err: 	... 11 more
2020-07-17 17:45:33.642 21528-21528/com.flutterwave.rave_android D/rave logger tag: Error parsing server response

**Comment by bolaware** [comment]
Heyy @mugabi0978, are you trying to Ghana Momo payments and it was returning an error, whats the error? The log shared isn't helpful

**Comment by mugabi0978** [comment]
> Heyy @mugabi0978, are you trying to Ghana Momo payments and it was returning an error, whats the error? The log shared isn't helpful

D/rave response: {"status":"error","message":"Connection lost: The server closed the connection.","data":{"name":"SequelizeConnectionError","message":"Connection lost: The server closed the connection.","parent":{"fatal":true,"code":"PROTOCOL_CONNECTION_LOST"},"original":{"fatal":true,"code":"PROTOCOL_CONNECTION_LOST"}}}

Thats the Error Hope its Useful.

**Comment by bolaware** [comment]
Can you re-try again, it seems to be a temporary downtime. @mugabi0978

**Comment by mugabi0978** [comment]
@bolaware the issue was resolved. i tested and now seems Okay. Thanks.
