### ISSUE TITLE
CRASH WHEN ENTERING PHONE NUMBER FOR MOBILE MONEY PAYMENTS

### ISSUE THREAD

**Issue by heromiyo** [Flutterwave/rave-android#261]
When i navigate to the payments page and try to enter the payment phone number Rave crashes with the error below 

Phone specs: 
Huawei P10 
Android Version: 10 

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hero76.tinkalerealestate, PID: 7027
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getBoundsOnScreen(android.graphics.Rect)' on a null object reference
        at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:484)
        at android.app.assist.AssistStructure.<init>(AssistStructure.java:1908)
        at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3471)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
I/Process: Sending signal. PID: 7027 SIG: 9

**Comment by heromiyo** [comment]
This crash only happens when user touches the phone number input field 
Stackoverflow shows this to be the issue https://stackoverflow.com/questions/45898228/android-attempt-to-invoke-virtual-method-void-android-view-view-getboundsonsc

**Comment by codeismail-waver** [comment]
Unable to reproduce this issue. I will be closing this issue now. kindly open a new issue if it persists.
https://github.com/user-attachments/assets/b24e5c6e-c1b2-44bf-a571-4420f6f099c9
