### ISSUE TITLE
Getting parsing error in Android target SDK 31

### ISSUE THREAD

**Issue by vasudevjogani** [Flutterwave/rave-android#279]
## Getting Parsing error 

https://ravesandboxapi.flutterwave.com/mockvbvpage?ref=FLW-MOCK-9e635c36ebdfef0d9884d498389089ea&code=00&message=Approved.%20Successful&receiptno=RN1636985366835

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:944)
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:897)
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:846)
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at com.flutterwave.raveandroid.rave_java_commons.NetworkRequestExecutor$1.onResponse(NetworkRequestExecutor.java:40)
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda1.run(Unknown Source:6)
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at android.os.Looper.loop(Looper.java:237)
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7948)
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2021-11-15 19:39:28.916 31771-31771/com.xyz.xyy W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
2021-11-15 19:39:28.917 31771-31771/com.xyz.xyy W/System.err: Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
2021-11-15 19:39:28.917 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
2021-11-15 19:39:28.917 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
2021-11-15 19:39:28.917 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
2021-11-15 19:39:28.917 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:932)
2021-11-15 19:39:28.917 31771-31771/com.xyz.xyy W/System.err: 	... 12 more

https://ravesandboxapi.flutterwave.com/mockvbvpage?ref=FLW-MOCK-9e635c36ebdfef0d9884d498389089ea&code=00&message=Approved.+Successful&receiptno=RN1636985366835&submitting_mock_form=12345

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
2021-11-15 19:40:40.184 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:944)
2021-11-15 19:40:40.184 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:897)
2021-11-15 19:40:40.184 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:846)
2021-11-15 19:40:40.184 31771-31771/com.xyz.xyy W/System.err:     at com.flutterwave.raveandroid.rave_java_commons.NetworkRequestExecutor$1.onResponse(NetworkRequestExecutor.java:40)
2021-11-15 19:40:40.185 31771-31771/com.xyz.xyy W/System.err:     at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
2021-11-15 19:40:40.185 31771-31771/com.xyz.xyy W/System.err:     at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda1.run(Unknown Source:6)
2021-11-15 19:40:40.185 31771-31771/com.xyz.xyy W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2021-11-15 19:40:40.185 31771-31771/com.xyz.xyy W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2021-11-15 19:40:40.185 31771-31771/com.xyz.xyy W/System.err:     at android.os.Looper.loop(Looper.java:237)
2021-11-15 19:40:40.185 31771-31771/com.xyz.xyy W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7948)
2021-11-15 19:40:40.185 31771-31771/com.xyz.xyy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-11-15 19:40:40.185 31771-31771/com.xyz.xyy W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2021-11-15 19:40:40.185 31771-31771/com.xyz.xyy W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
2021-11-15 19:40:40.186 31771-31771/com.xyz.xyy W/System.err: Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
2021-11-15 19:40:40.186 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
2021-11-15 19:40:40.186 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
2021-11-15 19:40:40.186 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
2021-11-15 19:40:40.186 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:932)
2021-11-15 19:40:40.186 31771-31771/com.xyz.xyy W/System.err: 	... 12 more
2021-11-15 19:40:40.187 31771-31771/com.xyz.xyy D/rave logger tag: Error parsing server response

POST https://ravesandboxapi.flutterwave.com/flwv3-pug/getpaidx/api/verify/mpesa 

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:944)
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:897)
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:846)
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at com.flutterwave.raveandroid.rave_java_commons.NetworkRequestExecutor$1.onResponse(NetworkRequestExecutor.java:40)
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda1.run(Unknown Source:6)
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at android.os.Looper.loop(Looper.java:237)
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7948)
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2021-11-15 19:40:41.739 31771-31771/com.xyz.xyy W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
2021-11-15 19:40:41.740 31771-31771/com.xyz.xyy W/System.err: Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
2021-11-15 19:40:41.740 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
2021-11-15 19:40:41.740 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
2021-11-15 19:40:41.740 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
2021-11-15 19:40:41.740 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:932)
2021-11-15 19:40:41.740 31771-31771/com.xyz.xyy W/System.err: 	... 12 more
2021-11-15 19:40:41.740 31771-31771/com.xyz.xyy D/rave logger tag: Error parsing server response

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
2021-11-15 19:40:41.902 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:944)
2021-11-15 19:40:41.902 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:897)
2021-11-15 19:40:41.902 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:846)
2021-11-15 19:40:41.902 31771-31771/com.xyz.xyy W/System.err:     at com.flutterwave.raveandroid.rave_java_commons.NetworkRequestExecutor$1.onResponse(NetworkRequestExecutor.java:40)
2021-11-15 19:40:41.902 31771-31771/com.xyz.xyy W/System.err:     at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
2021-11-15 19:40:41.902 31771-31771/com.xyz.xyy W/System.err:     at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda1.run(Unknown Source:6)
2021-11-15 19:40:41.902 31771-31771/com.xyz.xyy W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2021-11-15 19:40:41.902 31771-31771/com.xyz.xyy W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2021-11-15 19:40:41.903 31771-31771/com.xyz.xyy W/System.err:     at android.os.Looper.loop(Looper.java:237)
2021-11-15 19:40:41.903 31771-31771/com.xyz.xyy W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7948)
2021-11-15 19:40:41.903 31771-31771/com.xyz.xyy W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-11-15 19:40:41.903 31771-31771/com.xyz.xyy W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2021-11-15 19:40:41.903 31771-31771/com.xyz.xyy W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
2021-11-15 19:40:41.903 31771-31771/com.xyz.xyy W/System.err: Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
2021-11-15 19:40:41.903 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
2021-11-15 19:40:41.903 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
2021-11-15 19:40:41.903 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
2021-11-15 19:40:41.903 31771-31771/com.xyz.xyy W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:932)
2021-11-15 19:40:41.903 31771-31771/com.xyz.xyy W/System.err: 	... 12 more
2021-11-15 19:40:41.904 31771-31771/com.xyz.xyy D/rave logger tag: Error parsing server response)

## System Information

 - Operating system: 11 & 10
 - Rave version: 2.1.37

**Comment by malumbosiwale** [comment]
Did you eventually find a solution to this or we should target SDK 30?

**Comment by codeismail-waver** [comment]
Hello @vasudevjogani the error log shows it to be a failure in deserialising the network response. kindly confirm the object provided matches the response structure

**Comment by codeismail-waver** [comment]
I will be closing this issue now. kindly open a new issue if the experience persists.
