### ISSUE TITLE
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT

### ISSUE THREAD

**Issue by malumbosiwale** [Flutterwave/rave-android#282]
All transactions are successful but i cannot get a response from onActivityResult or ZambiaMobileMoneyPaymentCallback

Target SDK:  31
Device OS:  Android 11/ Android 12
Rave version: 2.1.37

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
2021-12-09 09:23:39.835 27672-27672/com.flutterwave.rave_android W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:944)
2021-12-09 09:23:39.835 27672-27672/com.flutterwave.rave_android W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:897)
2021-12-09 09:23:39.836 27672-27672/com.flutterwave.rave_android W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:846)

**Comment by Cherrio-LLC** [comment]
Log the response, or you're parsing it wrongly

**Comment by malumbosiwale** [comment]
I already created a workaround a while ago, the default code when imported gave that response, I supposed it parsed wrongly.

**Comment by Cherrio-LLC** [comment]
What was your work around??
