### ISSUE TITLE
 Activity com.flutterwave.raveandroid.RavePayActivity has leaked window DecorView@80ae752[RavePayActivity] that was originally added here         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1049)

### ISSUE THREAD

**Issue by musicmeetscode** [Flutterwave/rave-android#286]
## While using the ravepay default UI, everything works fine until a time that coincides with when a prompt should appear. The following error appears

``android.view.WindowLeaked: Activity com.flutterwave.raveandroid.RavePayActivity has leaked window DecorView@80ae752[RavePayActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1049)
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1023)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:450)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:114)
        at android.app.Dialog.show(Dialog.java:505)
        at com.flutterwave.raveandroid.ugmobilemoney.UgMobileMoneyFragment.showPollingIndicator(UgMobileMoneyFragment.java:307)
        at com.flutterwave.raveandroid.rave_presentation.ugmobilemoney.UgMobileMoneyHandler.requeryTx(UgMobileMoneyHandler.java:137)
        at com.flutterwave.raveandroid.rave_presentation.ugmobilemoney.UgMobileMoneyHandler$2.onSuccess(UgMobileMoneyHandler.java:108)
        at com.flutterwave.raveandroid.rave_presentation.ugmobilemoney.UgMobileMoneyHandler$2.onSuccess(UgMobileMoneyHandler.java:94)
        at com.flutterwave.raveandroid.rave_remote.RemoteRepository$GenericNetworkCallback.onSuccess(RemoteRepository.java:375)
        at com.flutterwave.raveandroid.rave_java_commons.NetworkRequestExecutor$1.onResponse(NetworkRequestExecutor.java:41)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda1.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)``

## System Information

 - Operating system: Android 11
 - Rave version: 3

**Comment by ma-za-kpe** [comment]
Hi guys, I'm also facing this issue on:
Android 10:
Rave Version:  implementation 'com.github.flutterwave.rave-android:rave_android:2.1.39'
Android Studio version :
Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022

![rave](https://user-images.githubusercontent.com/28810111/213570950-331ab234-66a3-447a-bd9f-96411dda43fd.PNG)
