### ISSUE TITLE
SDK throwing IllegalArgumentException after clicking on Pay button.

### ISSUE THREAD

**Issue by ominfowave** [Flutterwave/rave-android#6]
Fatal Exception: java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{196bd5ec V.E..... R......D 0,0-1026,348} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:416)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:342)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
       at android.app.Dialog.dismissDialog(Dialog.java:354)
       at android.app.Dialog.dismiss(Dialog.java:337)
       at com.flutterwave.raveandroid.card.CardFragment.showProgressIndicator(CardFragment.java:372)
       at com.flutterwave.raveandroid.card.CardPresenter$2.onError(CardPresenter.java:167)
       at com.flutterwave.raveandroid.data.NetworkRequestImpl$2.onResponse(NetworkRequestImpl.java:77)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5653)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by biodunalfet** [comment]
Hi,

What version of the sdk are you using?

**Comment by ominfowave** [comment]
Hello, 
i am using the latest sdk verion 1.0.4

**Comment by biodunalfet** [comment]
Ok. Can I see your initialization code?

**Comment by ominfowave** [comment]
Hello, Bellow is the initialization code i used.

//Create unique reference id for payment 
```
SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyymmdd_hhmmss");
String uniqueRef = simpleDateFormat.format(new Date());
```

//Initialize the Payment SDK
 ```
new RavePayManager(this).setAmount(Double.parseDouble(totalCost))
                .setCountry("NG")
                .setCurrency("NGN")
                .setEmail(prefs.getEmail())
                .setfName(prefs.getFirstName())
                .setlName(prefs.getLastName())
                .setNarration("Payment for " + categoryName + ", Job Code: " + jobCode + ", Date: " + jobDateTime) //This is a custom description added by the merchant.
                .setPublicKey(getString(R.string.rave_payment_public_key))
                .setSecretKey(getString(R.string.rave_payment_secret_key))
                .setTxRef(uniqueRef)
                .acceptAccountPayments(true)
                .acceptCardPayments(true)
                .onStagingEnv(false)
                .initialize();
```

**Comment by biodunalfet** [comment]
The issue is most likely your Activity. Please join our community slack https://flutterwavedevelopers.slack.com. I'll like to get a deeper look at your code.
