### ISSUE TITLE
Class Parcels does not exist

### ISSUE THREAD

**Issue by oolakan** [Flutterwave/rave-android#66]
When payment is initiated , it returns class not found exception. It refers to class Parcels.

dependency version i used was:
dependencies {
 		implementation 'com.github.Flutterwave:rave-android:1.0.34'
}

  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.parceler.Parcels" on path: DexPathList[[zip file "/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/base.apk", zip file "/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.swifta.pledgeapp-b-KfDkBgN3shnvEQMTISpQ==/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                          at com.flutterwave.raveandroid.RavePayManager.initialize(RavePayManager.java:169) 
                                                                          at com.swifta.pledgeapp.transaction.projects.DonateActivity.initiatePayment(DonateActivity.java:219) 
                                                                          at com.swifta.pledgeapp.transaction.projects.DonateActivity.onCreate(DonateActivity.java:89) 
                                                                          at android.app.Activity.performCreate(Activity.java:7023) 
                                                                          at android.app.Activity.performCreate(Activity.java:7014) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2758) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2883) 
                                                                          at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                          at android.os.Looper.loop(Looper.java:164) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

**Comment by biodunalfet** [comment]
@oolakan currently checking this

**Comment by AngaKoko** [comment]
I was having this issue as well, I added 
implementation 'org.parceler:parceler-api:1.1.9' and 
annotationProcessor 'org.parceler:parceler:1.1.9' 
to my gradle file. app level and it was resolved

**Comment by biodunalfet** [comment]
@AngaKoko thanks. This issue will be fixed in the next update. @oolakan you can use solve this by adding the two lines as suggested in the previous comment

**Comment by oolakan** [comment]
> I was having this issue as well, I added
> implementation 'org.parceler:parceler-api:1.1.9' and
> annotationProcessor 'org.parceler:parceler:1.1.9'
> to my gradle file. app level and it was resolved. I think this should be added in the documentation is this resolves the issue

After adding this to my gradle file, the error i get now is:

FATAL EXCEPTION: main
                                                                      Process: com.swifta.pledgeapp, PID: 23570
                                                                      java.lang.NoSuchFieldError: No static field rave_bankEditText of type I in class Lcom/flutterwave/raveandroid/R$id; or its superclasses (declaration of 'com.flutterwave.raveandroid.R$id' appears in /data/app/com.swifta.pledgeapp-YkB2DXBiZwi1WAVgHLmVmQ==/split_lib_slice_8_apk.apk)
                                                                          at com.flutterwave.raveandroid.account.AccountFragment.onCreateView(AccountFragment.java:93)
                                                                          at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
                                                                          at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                          at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
                                                                          at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
                                                                          at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
                                                                          at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
                                                                          at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
                                                                          at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                                                                          at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
                                                                          at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
                                                                          at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
                                                                          at android.view.View.measure(View.java:22753)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6685)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                                                                          at android.view.View.measure(View.java:22753)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6685)
                                                                          at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:739)
                                                                          at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:811)
                                                                          at android.view.View.measure(View.java:22753)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6685)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
                                                                          at android.view.View.measure(View.java:22753)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6685)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                                                                          at android.view.View.measure(View.java:22753)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6685)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at android.view.View.measure(View.java:22753)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6685)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
                                                                          at android.view.View.measure(View.java:22753)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6685)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                          at com.android.internal.policy.DecorView.onMeasure(DecorView.java:726)
                                                                          at android.view.View.measure(View.java:22753)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2535)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1562)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1830)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1450)
02-26 09:24:31.057 23570-23570/com.swifta.pledgeapp E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7023)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:924)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:732)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:664)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:910)
                                                                          at android.os.Handler.handleCallback(Handler.java:790)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

**Comment by biodunalfet** [comment]
@oolakan are you using proguard?

**Comment by AngaKoko** [comment]
add all these to you gradle file 

implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.1'
    implementation 'org.parceler:parceler-api:1.1.9'
    annotationProcessor 'org.parceler:parceler:1.1.9'
    implementation 'com.squareup.retrofit2:converter-scalars:2.1.0'
    implementation 'com.scottyab:aescrypt:0.0.1'

**Comment by oolakan** [comment]
Alright, thanks, will iclude that now

**Comment by oolakan** [comment]
> @oolakan add all these to you gradle file. All these includes the other two
> 
> implementation 'com.squareup.retrofit2:retrofit:2.4.0'
> implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
> implementation 'com.squareup.okhttp3:logging-interceptor:3.9.1'
> implementation 'org.parceler:parceler-api:1.1.9'
> annotationProcessor 'org.parceler:parceler:1.1.9'
> implementation 'com.squareup.retrofit2:converter-scalars:2.1.0'
> implementation 'com.scottyab:aescrypt:0.0.1'

I included all these now and rebuild. I'm still getting the same error.
 
java.lang.NoSuchFieldError: No static field rave_bankEditText of type I in class Lcom/flutterwave/raveandroid/R$id; or its superclasses (declaration of 'com.flutterwave.raveandroid.R$id' appears in /data/app/com.swifta.pledgeapp-VuvOIYvPQULUjz7ukwe1Fw==/split_lib_slice_8_apk.apk)

 implementation 'com.github.Flutterwave:rave-android:1.0.34' - This is the version im using.

**Comment by oolakan** [comment]
> @oolakan are you using proguard?

No

**Comment by AngaKoko** [comment]
@oolakan can we implementations in your gradle file?
and add 
classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'

in your dependencies on project level gradle file

**Comment by jeremiahVaris** [comment]
@oolakan 
Please upgrade the dependency version to 1.0.35. This issue was fixed in that upgrade.

**Comment by oolakan** [comment]
alright, guys, i will do as suggested. Thanks

**Comment by oolakan** [comment]
> @oolakan can we see implementations in your gradle file?
> and add
> classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'
> 
> in your dependencies on project level gradle file

I have added this to the gradle file at project level... it's still same error:

java.lang.NoSuchFieldError: No static field rave_bankEditText of type I in class Lcom/flutterwave/raveandroid/R$id; or its superclasses (declaration of 'com.flutterwave.raveandroid.R$id' appears in /data/app/com.swifta.pledgeapp-_mO8esRigU3jC1WiS5PHBA==/split_lib_slice_8_apk.apk)

**Comment by oolakan** [comment]
> @oolakan
> Please upgrade the dependency version to 1.0.35. This issue was fixed in that upgrade.

I have upgraded and it's still same error.

**Comment by jeremiahVaris** [comment]
It seems you might have a Layout file with the same name as one of the files in the SDK (probably "fragment_account.xml") and it causes a conflict. Please rename the file and rebuild.

**Comment by oolakan** [comment]
> It seems you might have a Layout file with the same name as one of the files in the SDK (probably "fragment_account.xml") and it causes a conflict. Please rename the file and rebuild.

I had a layout file with that name. After changing the name, it worked to the point of entering Card PIN after which it crashed. This is the error log:

Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65980, result=111, data=Intent { (has extras) }} to activity {com.swifta.pledgeapp/com.flutterwave.raveandroid.RavePayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.flutterwave.raveandroid.Payload.setPin(java.lang.String)' on a null object reference
                                                                          at android.app.ActivityThread.deliverResults(ActivityThread.java:4295)
                                                                          at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3580)
                                                                          at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3648) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2889) 
                                                                          at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                          at android.os.Looper.loop(Looper.java:164) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6523) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857) 
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.flutterwave.raveandroid.Payload.setPin(java.lang.String)' on a null object reference
                                                                          at com.flutterwave.raveandroid.card.CardPresenter.chargeCardWithSuggestedAuthModel(CardPresenter.java:197)
                                                                          at com.flutterwave.raveandroid.card.CardFragment.onActivityResult(CardFragment.java:397)
                                                                          at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:156)
                                                                          at android.app.Activity.dispatchActivityResult(Activity.java:7290)
                                                                          at android.app.ActivityThread.deliverResults(ActivityThread.java:4291)

**Comment by biodunalfet** [comment]
Hi @oolakan can you paste your build.gradle file here?

**Comment by oolakan** [comment]
> Hi @oolakan can you paste your build.gradle file here?

apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId ".........."
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 9
        versionName "1.0.8"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildToolsVersion '27.0.3'
}
allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}


buildscript {
    repositories {
        jcenter()
    }
}



dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:support-vector-drawable:27.1.1'
    implementation "com.android.support:cardview-v7:27.1.1"
    implementation "com.jakewharton:butterknife:8.3.0"
    annotationProcessor "com.jakewharton:butterknife-compiler:8.7.0"
    implementation "com.squareup.retrofit2:retrofit:2.4.0"
    implementation "com.squareup.retrofit2:converter-gson:2.3.0"
    implementation "com.squareup.retrofit2:adapter-rxjava:2.0.2"
    implementation "io.reactivex:rxandroid:1.2.1"
    implementation "io.reactivex:rxjava:1.1.6"
    implementation "com.google.code.gson:gson:2.6.2"
    implementation "com.getbase:floatingactionbutton:1.10.1"
    implementation "de.hdodenhof:circleimageview:1.3.0"
    implementation "com.theartofdev.edmodo:android-image-cropper:2.3.1"
    implementation 'com.github.aakira:expandable-layout:1.6.0@aar'
    implementation 'com.daimajia.slider:library:1.1.5@aar'
    implementation 'com.github.Flutterwave:rave-android:1.0.35'
    implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.1'
    implementation 'org.parceler:parceler-api:1.1.9'
    annotationProcessor 'org.parceler:parceler:1.1.9'
    implementation 'com.squareup.retrofit2:converter-scalars:2.1.0'
    implementation 'com.scottyab:aescrypt:0.0.1'
    implementation "com.squareup.picasso:picasso:2.5.2"
    implementation 'com.nineoldandroids:library:2.4.0'
}

**Comment by biodunalfet** [comment]
@oolakan you need to remove all these
```
implementation 'com.squareup.retrofit2:retrofit:2.4.0'
implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
implementation 'com.squareup.okhttp3:logging-interceptor:3.9.1'
implementation 'org.parceler:parceler-api:1.1.9'
annotationProcessor 'org.parceler:parceler:1.1.9'
implementation 'com.squareup.retrofit2:converter-scalars:2.1.0'
implementation 'com.scottyab:aescrypt:0.0.1'
```

and run the app. If you're still experiencing this, join our [Slack community](https://join.slack.com/t/flutterwavedevelopers/shared_invite/enQtMjU2MjkyNDM5MTcxLWFlOWNlYmE5MTIxNjAwYzc5MDVjZjNhYTJjNTA0ZTQyNDJlMDhhZjJkN2QwZGJmNWMyODhlYjMwNGUyZDQxNTE) so I can get to understand the issue better.
