### ISSUE TITLE
NullPointerException on validation inside SDK

### ISSUE THREAD

**Issue by ominfowave** [Flutterwave/rave-android#7]
Hello, we received this crash report from our client, seems like SDK is trying to read some message from error response from the param which is not exist.

```
Fatal Exception: java.lang.NullPointerException: println needs a message
       at android.util.Log.println_native(Log.java)
       at android.util.Log.d(Log.java:139)
       at com.flutterwave.raveandroid.card.CardFragment.validateDetails(CardFragment.java:323)
       at com.flutterwave.raveandroid.card.CardFragment.onClick(CardFragment.java:243)
       at android.view.View.performClick(View.java:4438)
       at android.view.View$PerformClick.run(View.java:18422)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5019)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by biodunalfet** [comment]
Fixed in version 1.0.5
