### ISSUE TITLE
Error in RavePayActivity .Binary XML file line #9: Binary XML file line #12: Error inflating class

### ISSUE THREAD

**Issue by prashant1137** [Flutterwave/rave-android#92]
I have Implemented Flutterwave as per the documentation and added related libraries in gradle whatever possible libraries it require to solve the crash as below :
    implementation 'com.github.Flutterwave:rave-android:1.0.27'
    implementation 'org.parceler:parceler-api:1.1.9
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'
    implementation 'com.squareup.okhttp3:okhttp:3.9.0'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-scalars:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.scottyab:aescrypt:0.0.1'

but when I click on a button to parse the RavePayManager and initialize it like below :
new RavePayManager(this).setAmount(amount_double)
                        .setCountry("GH")
                        .setCurrency(currency)
                        .setEmail(email)
                        .setfName(fName)
                        .setlName(lName)
                        .setPublicKey("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
                        .setSecretKey("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
                        .acceptAccountPayments(true)
                        .acceptCardPayments(true)
                        .onStagingEnv(false)
                        .setTxRef(txRef)
                        .withTheme(R.style.DefaultTheme)
                        .initialize();

 then it directly gives crash as below in "RavePayActivity XML" file what should I do to overcome?
Error : Unable to start activity ComponentInfo/com.flutterwave.raveandroid.RavePayActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #12: Error inflating class <unknown>

**Comment by biodunalfet** [comment]
@prashant1137 please can you paste the full error? This is usually caused when you have a layout file that has the same name as one of the layout files in the sdk.

**Comment by prashant1137** [comment]
@biodunalfet  ,
I tested RavePayActivity.java's Layout file activity_rav_pay.xml , as you suggested check the same name layout file but I don't have any such layout file from my side, and the whole error is as below,

 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.telafric.dialer, PID: 25276
    java.lang.RuntimeException: Unable to start activity ComponentInfo{/com.flutterwave.raveandroid.RavePayActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #12: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3364)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3548)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #12: Error inflating class <unknown>
     Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class <unknown>
     Caused by: java.lang.reflect.InvocationTargetException

**Comment by ankomahpounds** [comment]
Good
